name: cicd-pipeline

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
  
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: '21.6.1'
  
        - name: Installing Dependencies
          run: npm install
          working-directory: ./backend
  
    test:
      runs-on: ubuntu-latest
      needs: build
  
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
  
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: '21.6.1'
  
        - name: Installing Dependencies
          run: npm install
          working-directory: ./backend
  
        - name: Run endpoint tests
          run: npm test
          working-directory: ./backend
  
    deploy:
      runs-on: ubuntu-latest
      needs: test
      environment: staging
  
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
  
        - name: Deploy to Staging
          run: |
            echo "fake deployment to staging"
  