name: cicd-pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '21.6.1'

      - name: Installing Dependencies
        run: npm install
        working-directory: ./backend

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '21.6.1'

      - name: Installing Dependencies
        run: npm install
        working-directory: ./backend

      - name: Run Endpoint Tests
        run: npm test
        working-directory: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Staging
        run: |
          echo "fake deployment to staging"

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      # Notify the Discord Channel when a Build Fails
      - name: Notify on Build Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -d "{\"content\": \"⚠️ The CI/CD pipeline encountered an error on commit: $GITHUB_SHA. Please investigate the issue.\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      # Notify the Discord Channel when a Build Succeeds
      - name: Notify on Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -d "{\"content\": \"✅ The CI/CD pipeline successfully completed for commit: $GITHUB_SHA. Good job!\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
